[package]
name = "rget"
version = "0.1.0"
edition = "2024"
authors = ["Ryan Schindler <rfs.4bus@gmail.com>"]

[dependencies]
clap = "2.26.0"
indicatif = "0.18.3"
console = "0.16.2"
reqwest = "0.13.1"
url = "2.5.8"